project:
  name: quickstart-skillnet-xstoreoffice
  owner: quickstart@amazon.com
  package_lambda: false
  regions:
  - af-south-1
  - ap-east-1
  - ap-northeast-1
  - ap-northeast-2
  - ap-northeast-3
  - ap-south-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-north-1
  - eu-south-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - me-south-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  s3_bucket: ''
tests:
  xstoreoffice:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      RemoteAccessCIDR: 0.0.0.0/0
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: quickstart-skillnet-xstoreoffice/
      DeployServerSSLCertificateArn: override
      XAdminSSLCertificateArn: override
      AdminPassword: $[taskcat_genpass_16]
    regions:
    - us-east-1
    s3_bucket: ''
    template: templates/xstore-entrypoint-new-vpc.template.yaml
