// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Post deployment steps
// If Post-deployment steps are required, add them here. If not, remove the heading
Disable the Auto Scaling Group for the Oracle WebLogic Cluster and Apache Tomcat server.

. Select Auto Scaling Group for Oracle WebLogic Server.
. In the *Details* tab, select the *Edit* button.
. In the *Suspended Processes* list box, select all the processes to suspend.
. Repeat steps 1-3 for Apache Tomcat Server.

== Storage
* As shown in <<architecture1>>, Amazon Data Lifecycle Manager (DLM) is used to automate the creation, retention, and deletion of snapshots of the Amazon Elastic Block Storage (EBS) volumes.

DLM is configured as follows:

. The EC2 tag (Name: *LCM_TAG* , Value: *XSTORE*) key-value pair is used to take snapshots.
. The most recent three snapshots are retained. 
. A copy of each snapshot is stored in another AWS Region for data redundancy.

== Infrastructure Monitoring

After implementing your Oracle WebLogic applications in the AWS Cloud, you can continue to use the monitoring tools you are familiar with to monitor your Oracle WebLogic environment and the application you deployed on WebLogic.

You can use Fusion Middleware Control, the Oracle WebLogic Server Administration Console, or the command line (using the https://docs.oracle.com/middleware/1213/wls/WLSTC/reference.htm#WLSTC416[WSLT state command^]) to monitor your Oracle WebLogic infrastructure components. This includes WebLogic domains, Managed Servers, and clusters. You can also monitor the Java applications deployed and get information such as the state of your application, the number of active sessions, and response times. 

For more information about how to monitor Oracle WebLogic, see the https://www.oracle.com/middleware/technologies/weblogic.html[Oracle WebLogic documentation].

You can also use Amazon CloudWatch to monitor the AWS Cloud resources the applications you run on AWS. Amazon CloudWatch enables you to monitor your AWS resources in near real-time, including Amazon EC2 instances, Amazon EBS volumes, Amazon EFS, Elastic Load Balancers, and Amazon RDS database instances. Metrics such as CPU utilization, latency, and request counts are provided automatically for these AWS resources. You can also supply your own logs or custom application and system metrics, such as memory usage, transaction volumes, or error rates, which Amazon CloudWatch will also monitor.

With Amazon CloudWatch alarms, you can set a threshold on metrics and trigger an action when that threshold is exceeded. For example, you can create an alarm that is triggered when the CPU utilization on an EC2 instance crosses a threshold. You can also configure a notification of the event to be sent through SMS or email. Real-time alarms for metrics and events enable you to minimize downtime and potential business impact. 

== Support

The {partner-company-name} support team is standing by to assist you with setting up {partner-product-name} on your AWS environment. Send an email to support_xstoreoffice@skillnetinc.com to contact the support team.

Automating snapshot management accomplishes the following:

** Protects valuable data by enforcing a regular backup schedule.
** Retains backups as required by auditors or for internal compliance.
** Reduces storage costs by deleting outdated backups.

In the reference architecture, we use Amazon EFS for shared storage of the following:

** WebLogic binaries
** Domain configurations
** Common scripts
** Logs