// Add steps as necessary for accessing the software, post-configuration, and testing. Don’t include full usage instructions for your software, but add links to your product documentation for that information.
//Should any sections not be applicable, remove them

== Post-deployment steps
// If Post-deployment steps are required, add them here. If not, remove the heading
Disable the Auto Scaling group for the Oracle WebLogic cluster and Apache Tomcat server.

. Choose the Auto Scaling group for the Oracle WebLogic server.
. On the *Details* tab, choose the *Edit* button.
. On the *Suspended processes* list box, select all the processes to suspend.
. Repeat steps 1–3 for Apache Tomcat Server.

== Storage
As shown in <<architecture1>>, Amazon DLM is used to automate the creation, retention, and deletion of snapshots of the Amazon EBS volumes.

Amazon DLM is configured as follows:

. Uses EC2 tag (name: *LCM_TAG* , value: *XSTORE*) key-value pairs to take snapshots.
. Retains the most recent three snapshots. 
. Stores a copy of each snapshot in another AWS Region for redundancy.

== Infrastructure monitoring

After implementing your Oracle WebLogic applications in the AWS Cloud, monitor your Oracle WebLogic environment and the deployed application on WebLogic.

You can use Fusion Middleware Control, the Oracle WebLogic Server Administration Console, or the command line (using the https://docs.oracle.com/middleware/1213/wls/WLSTC/reference.htm#WLSTC416[WSLT state command^]) to monitor your Oracle WebLogic infrastructure components. This includes WebLogic domains, Managed Servers, and clusters. You can also monitor the Java applications deployed and get information such as the state of your application, the number of active sessions, and response times. 

For more information about how to monitor Oracle WebLogic, see the https://www.oracle.com/middleware/technologies/weblogic.html[Oracle WebLogic Server^].

You can also use Amazon CloudWatch to monitor the AWS Cloud resources the applications you run on AWS. Amazon CloudWatch monitors your AWS resources in real-time, including Amazon EC2 instances, Amazon EBS volumes, Amazon EFS, Elastic Load Balancers, and Amazon RDS database instances. Metrics such as CPU utilization, latency, and request counts are provided automatically for these AWS resources. You can also supply your own logs or custom application and system metrics, such as memory usage, transaction volumes, or error rates, which Amazon CloudWatch  also monitors.

With Amazon CloudWatch alarms, you can set a threshold on metrics and trigger an action when that threshold is exceeded. For example, you can create an alarm that is triggered when the CPU utilization on an EC2 instance crosses a threshold. You can also configure an email or SMS notification of the event to be sent through Amazon Simple Notification Service (Amazon SNS). Real-time alarms for metrics and events help you to minimize downtime and business impacts. 

== Support

The {partner-company-name} support team is standing by to assist you with setting up {partner-product-name} on your AWS environment. Send an email to support_xstoreoffice@skillnetinc.com to contact the support team.

Automating snapshot management accomplishes the following:

** Protects valuable data by enforcing a regular backup schedule.
** Retains backups as required by auditors or for internal compliance.
** Reduces storage costs by deleting outdated backups.

In the reference architecture, we use Amazon EFS for shared storage of the following:

** WebLogic binaries
** Domain configurations
** Common scripts
** Logs