AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates a VPC infrastructure for a multi-AZ, multi-tier
  deployment of xStoreOffice on AWS. It deploys a VPC with a bastion host.
    WARNING This template creates Amazon EC2 instances and related resources. You will be billed for the AWS resources used if you create a stack from this template. (qs-1r53pe6g1)
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Parameters for deploying into a new VPC"
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - AvailabilityZones
      - VPCCIDR
      - PrivateSubnet1CIDR
      - PrivateSubnet2CIDR
      - PublicSubnet1CIDR
      - PublicSubnet2CIDR
      - RemoteAccessCIDR
    - Label:
        default: XStore Office environment configuration
      Parameters:
      - EnvironmentSize
      - KeyPairName
      - StackPrefix
      - PuppetServerFQDN
      - DeployServerSSLCertificateArn
      - XAdminSSLCertificateArn
    - Label:
        default: WebLogic cluster storage configuration
      Parameters:  
      - EFSVolumeName
      - EFSMountPoint
    - Label:
        default: Oracle database configuration
      Parameters:
      - DBName
      - Admin
      - AdminPassword
      - DBAllocatedStorage
      - DBInstanceClass
      - OracleEdition
      - Family 
      - Compatible
      - EngineVersion
      - LicenseModel
    - Label:
        default: Backup configuration
      Parameters:
      - DLMCrossRegionCopy
    - Label:
        default: AWS Quick Start configuration
      Parameters:
      - QSS3BucketName
      - QSS3BucketRegion
      - QSS3KeyPrefix
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      PrivateSubnet1CIDR:
        default: Private subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private subnet 2 CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public subnet 2 CIDR
      RemoteAccessCIDR:
        default: Allowed bastion external access CIDR
      VPCCIDR:
        default: VPC CIDR
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      EnvironmentSize:
        default: Environment size
      KeyPairName:
        default: Key-pair name
      StackPrefix:
        default: Stack name prefix
      PuppetServerFQDN:
        default: Puppet server FQDN
      DeployServerSSLCertificateArn:
        default: SSL certificate ARN for deployment server ALB
      XAdminSSLCertificateArn:
        default: SSL certificate ARN for XAdmin server ALB
      EFSVolumeName:
        default: EFS volume name
      EFSMountPoint:
        default: EFS volume mount point
      DBName:
        default: Database name
      Admin:
        default: Administrator 
      AdminPassword:
        default: Administrator password
      DBAllocatedStorage:
        default: Database allocated storage
      DBInstanceClass:
        default: Database instance class
      OracleEdition:
        default: Oracle edition
      Family:
        default: Oracle family
      Compatible:
        default: Oracle version
      EngineVersion:
        default: Oracle engine version
      LicenseModel:
        default: Oracle license model
      DLMCrossRegionCopy:
        default: DLM cross-Region copy
Parameters:
  AvailabilityZones:
    Description: Choose two Availability Zones for the subnets in the VPC. Your first selection is Availability Zone 1 in the deployment, and your second selection is Availability Zone 2.
    Type: List<AWS::EC2::AvailabilityZone::Name>
  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28.
    Default: 10.0.0.0/19
    Description: CIDR block for private subnet 1, located in Availability Zone 1.
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28.
    Default: 10.0.32.0/19
    Description: CIDR block for private subnet 2, located in Availability Zone 2.
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28.
    Default: 10.0.128.0/20
    Description: CIDR block for the public (DMZ) subnet 1, located in Availability
      Zone 1.
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28.
    Default: 10.0.144.0/20
    Description: CIDR block for the public (DMZ) subnet 2, located in Availability
      Zone 2.
    Type: String
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. When using your own bucket, you must specify this value.
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slashes (/).
    Default: quickstart-skillnet-xstoreoffice/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slashes (/).
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: CIDR IP range that is permitted to access the bastion host. We recommend that you set this value to a trusted IP range.
    Type: String
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28.
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC.
    Type: String
  DLMCrossRegionCopy:
    Description: Cross-Region to copy the EC2 instance snapshots for backup. 
    Type: String
    Default: us-east-2
  EnvironmentSize:
    Type: String
    Default: Small
    AllowedValues:
      - Small
      - Medium
      - Large
    Description: XStore Office environment size (small, medium, or large).
  KeyPairName:
    Description: EC2 key-pair name.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 key pair.
  StackPrefix:
    Type: String
    MinLength: "1"
    MaxLength: "20"
    AllowedPattern: "[a-zA-Z0-9]*"
    Description: Prefix name for all the associated resources in the stack.
    Default: XStoreOffice
  PuppetServerFQDN:
    Type: String
    Default: "puppet.skillnetaws.com"
    Description: Assign fully qualified domain name for Puppet server.
  DeployServerSSLCertificateArn:
    Type: String
    Description: SSL certificate ARN for deployment server load balancer.
  XAdminSSLCertificateArn:
    Type: String
    Description: SSL certificate ARN for XAdmin Application Load Balancer.
  EFSVolumeName:
    Description: Amazon EFS volume name.
    Type: String
    MinLength: '1'
    Default: XStoreOfficeWlsEFS
  EFSMountPoint:
    Description: Linux mount point for the Amazon EFS volume.
    Type: String
    MinLength: '1'
    Default: "/home/oracle"
  DBName:
    Default: orcldb
    Description: Oracle System ID (SID).
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  Admin:
    Default: xstore
    Description: Oracle database administrator name.
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  AdminPassword:
    Default: Test1234
    NoEcho: 'true'
    Description: Oracle database administrator password.
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: Must contain only alphanumeric characters.
  DBAllocatedStorage:
    ConstraintDescription: Must be between 100 and 4096 GiB.
    AllowedValues:
    - 100
    - 500
    - 1024
    - 2048
    - 4096
    Default: '100'
    Description: Size of the database in gigabytes (GiB).
    Type: Number
  DBInstanceClass:
    AllowedValues:
    - db.m3.large
    - db.m3.xlarge
    - db.m3.2xlarge
    - db.m4.2xlarge
    - db.r4.large
    - db.r4.16xlarge
    - db.r4.8xlarge
    - db.r4.4xlarge
    ConstraintDescription: Choose a valid database instance type.
    Default: db.r4.large
    Description: Name of the compute and memory capacity class of the database instance.
    Type: String
  OracleEdition:
    AllowedValues:
    - oracle-ee
    - oracle-se
    - oracle-se1
    - oracle-se2 
    ConstraintDescription: Choose a valid Oracle edition.
    Default: oracle-ee
    Description: Oracle edition.
    Type: String
  Family:
    AllowedValues:
    - oracle-ee-11.2
    - oracle-ee-12.1
    - oracle-ee-12.2
    - oracle-ee-18.0
    - oracle-ee-19.0
    - oracle-se-11.2
    - oracle-se-12.1
    - oracle-se-12.2
    - oracle-se-18.0
    - oracle-se-19.0
    - oracle-se1-11.2
    - oracle-se1-12.1
    - oracle-se1-12.2
    - oracle-se1-18.0
    - oracle-se1-19.0
    - oracle-se2-11.2
    - oracle-se2-12.1
    - oracle-se2-12.2
    - oracle-se2-18.0
    - oracle-se2-19.0    
    ConstraintDescription: Choose a valid Oracle family.
    Default: oracle-ee-12.1
    Description: Oracle family engine.
    Type: String
  Compatible:
    AllowedValues:
    - 12.1.0.2
    - 12.2.0.1
    - 18.0.0.0
    - 19.0.0.0
    ConstraintDescription: Choose a version compatible with the selected Oracle family.
    Default: 12.1.0.2
    Description: Oracle version that is compatible with the Oracle family (e.g., 12.1.0.2.)
    Type: String
  EngineVersion:
    AllowedValues:
    - 11.2.0.4.v1
    - 11.2.0.4.v2
    - 11.2.0.4.v3
    - 11.2.0.4.v4
    - 11.2.0.4.v5
    - 11.2.0.4.v6
    - 11.2.0.4.v7
    - 11.2.0.4.v8
    - 11.2.0.4.v9
    - 11.2.0.4.v10
    - 11.2.0.4.v11
    - 11.2.0.4.v12
    - 11.2.0.4.v13
    - 11.2.0.4.v14
    - 11.2.0.4.v15
    - 11.2.0.4.v16
    - 11.2.0.4.v17
    - 11.2.0.4.v18
    - 11.2.0.4.v19
    - 11.2.0.4.v20
    - 11.2.0.4.v21
    - 11.2.0.4.v22
    - 11.2.0.4.v23
    - 12.1.0.2.v1
    - 12.1.0.2.v2
    - 12.1.0.2.v3
    - 12.1.0.2.v4
    - 12.1.0.2.v5
    - 12.1.0.2.v6
    - 12.1.0.2.v7
    - 12.1.0.2.v8
    - 12.1.0.2.v9
    - 12.1.0.2.v10
    - 12.1.0.2.v11
    - 12.1.0.2.v12
    - 12.1.0.2.v13
    - 12.1.0.2.v14
    - 12.1.0.2.v15
    - 12.1.0.2.v16
    - 12.1.0.2.v17
    - 12.1.0.2.v18
    - 12.1.0.2.v19
    - 12.2.0.1.ru-2018-10.rur-2018-10.r1
    - 12.2.0.1.ru-2019-01.rur-2019-01.r1
    - 12.2.0.1.ru-2019-04.rur-2019-04.r1
    - 12.2.0.1.ru-2019-07.rur-2019-07.r1
    - 12.2.0.1.ru-2019-10.rur-2019-10.r1
    - 12.2.0.1.ru-2020-01.rur-2020-01.r1
    - 18.0.0.0.ru-2020-01.rur-2020-01.r1
    - 18.0.0.0.ru-2019-07.rur-2019-07.r1
    - 18.0.0.0.ru-2019-10.rur-2019-10.r1
    - 19.0.0.0.ru-2020-01.rur-2020-01.r1
    - 19.0.0.0.ru-2019-07.rur-2019-07.r1
    - 19.0.0.0.ru-2019-10.rur-2019-10.r1    
    ConstraintDescription: Choose an engine version compatible with the selected Oracle family.
    Default: 12.1.0.2.v7
    Description: Oracle engine version compatible with the family (e.g., 12.1.0.2.v7.)
    Type: String
  LicenseModel:
    AllowedValues:
    - license-included
    - bring-your-own-license
    ConstraintDescription: Choose a valid Oracle license.
    Default: bring-your-own-license
    Description: Oracle license type.
    Type: String
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        AvailabilityZones: !Join [',', !Ref 'AvailabilityZones']
        KeyPairName: !Ref KeyPairName
        NumberOfAZs: '2'
        PrivateSubnet1ACIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2ACIDR: !Ref PrivateSubnet2CIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        VPCCIDR: !Ref VPCCIDR
  BastionStack:
    DependsOn: VPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/linux-bastion.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        QSS3BucketName: !Ref QSS3BucketName
        QSS3BucketRegion: !Ref QSS3BucketRegion
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        KeyPairName: !Ref KeyPairName
        PublicSubnet1ID: !GetAtt VPCStack.Outputs.PublicSubnet1ID
        PublicSubnet2ID: !GetAtt VPCStack.Outputs.PublicSubnet2ID
        RemoteAccessCIDR: !Ref RemoteAccessCIDR
        VPCID: !GetAtt VPCStack.Outputs.VPCID
  xStoreStack:
    DependsOn: VPCStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/xstore-qs-main.template.yaml'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        QSS3BucketName: !Ref QSS3BucketName
        QSS3BucketRegion: !Ref QSS3BucketRegion
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        UserSpecifiedVPCId: !GetAtt VPCStack.Outputs.VPCID
        Subnet1ID: !GetAtt VPCStack.Outputs.PrivateSubnet1AID
        Subnet2ID: !GetAtt VPCStack.Outputs.PrivateSubnet2AID
        EnvironmentSize: !Ref EnvironmentSize
        KeyPairName: !Ref KeyPairName
        StackPrefix: !Ref StackPrefix
        ProxyServer: !Join [ '' , ['http://', !GetAtt BastionStack.Outputs.EIP1, ':3128' ] ]
        PuppetServerFQDN: !Ref PuppetServerFQDN
        DeployServerSSLCertificateArn: !Ref DeployServerSSLCertificateArn
        XAdminSSLCertificateArn: !Ref XAdminSSLCertificateArn
        EFSVolumeName: !Ref EFSVolumeName
        EFSMountPoint: !Ref EFSMountPoint
        DBName: !Ref DBName
        Admin: !Ref Admin
        AdminPassword: !Ref AdminPassword
        DBAllocatedStorage: !Ref DBAllocatedStorage
        DBInstanceClass: !Ref DBInstanceClass
        OracleEdition: !Ref OracleEdition
        Family : !Ref Family 
        Compatible: !Ref Compatible
        EngineVersion: !Ref EngineVersion
        LicenseModel: !Ref LicenseModel
        DLMCrossRegionCopy: !Ref DLMCrossRegionCopy
