---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates a VPC infrastructure for Oracle XStore Application deployment on AWS.
  This template creates VPC, 2 Private Subnets, All required Security Groups, VPC End points for S3 bucket
  and Monitoring, Data lifecycle Manager for instance backup, Instance Profile for S3 and monitoring access.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
        - VpcCIDR
        - Subnet1CIDR
        - Subnet2CIDR
      - Label:
          default: Backup Configuration
        Parameters:
        - DLMCrossRegionCopy
      - Label:
          default: AWS Quick Start configuration
        Parameters:
          - QSS3BucketName
          - QSS3BucketRegion
          - QSS3KeyPrefix
      - Label:
          default: XStore environment configuration
        Parameters:
          - EnvironmentSize
          - KeyPairName
          - StackPrefix
          - ProxyServer
          - PuppetServerFQDN
    ParameterLabels:
      VpcCIDR:
        default: VPC CIDR
      Subnet1CIDR:
        default: Private subnet 1 CIDR
      Subnet2CIDR:
        default: Private subnet 2 CIDR
      DLMCrossRegionCopy:
        default: DLM Cross Region Name
      QSS3BucketName:
        default: Quick Start S3 bucket
      QSS3BucketRegion:
        default: Quick Start S3 bucket Region
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      EnvironmentSize:
        default: Environment Size
      KeyPairName:
        default: Key Pair Name
      StackPrefix:
        default: Stack Name Prefix
      ProxyServer:
        default: Proxy Server URL
      PuppetServerFQDN:
        default: Puppet Server FQDN
Parameters:
  VpcCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.10.0.0/24
    Description: CIDR block for VPC
    Type: String
  Subnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.10.0.0/25
    Description: CIDR block for subnet1
    Type: String
  Subnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.10.0.128/25
    Description: CIDR block for subnet2
    Type: String
  DLMCrossRegionCopy:
    Description: DLM for cross region copy  
    Type: String
    Default: us-east-2
  QSS3BucketName:
    AllowedPattern: "^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription: "Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Default: skillnet-aws-isv-workload-migration
    Description: "S3 bucket name for the Quick Start assets. Quick Start bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-)."
    Type: String
  QSS3BucketRegion:
    Default: 'us-east-1'
    Description: "AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. If you use your own bucket, specify that value."
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: "^[0-9a-zA-Z-/]*$"
    ConstraintDescription: "Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Default: xstore-quickstart/
    Description: "S3 key prefix for the Quick Start assets. Quick Start key prefix can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/)."
    Type: String
  EnvironmentSize:
    Type: String
    Default: Small
    AllowedValues:
      - Small
      - Medium
      - Large
    Description: Select Environment Size (S,M,L)
  KeyPairName:
    Description: The EC2 Key Pair to allow SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  StackPrefix:
    Type: String
    MinLength: "1"
    MaxLength: "20"
    AllowedPattern: "[a-zA-Z0-9]*"
    Description: The prefix to all the associated resources in the stack
    Default: XStore
  ProxyServer:
    Type: String
    Default: "http://192.168.50.197:3128"
  PuppetServerFQDN:
    Type: String
    Default: "puppet.skillnetaws.com"
Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
Resources:
  LandingZone:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Sub
          - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}xstore-landingzone-template.yaml
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        Subnet1CIDR: !Ref Subnet1CIDR
        Subnet2CIDR: !Ref Subnet2CIDR
        DLMCrossRegionCopy: !Ref DLMCrossRegionCopy
  PuppetServer:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL:
        !Sub
          - https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}xstore-puppetserver-template.yaml
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        EnvironmentSize: !Ref EnvironmentSize      
        Subnet:
          Fn::GetAtt:
          - LandingZone
          - Outputs.XStoreSubnet1ID
        SecurityGroups:
          Fn::GetAtt:
          - LandingZone
          - Outputs.XStoreSecurityGroup
        KeyPairName: !Ref KeyPairName
        StackPrefix: !Ref StackPrefix
        ProxyServer: !Ref ProxyServer
        IamInstanceProfile:
          Fn::GetAtt:
          - LandingZone
          - Outputs.XStoreInstanceProfile
        PuppetServerFQDN: !Ref PuppetServerFQDN
         
  